In [1]:
#loading the data
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\dell\Downloads\top_anime_dataset.csv")

In [5]:
df.head()

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,scored_by,rank,popularity,members,favorites,synopsis,year,genres,studios,url
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,823434,1.0,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,62148,2.0,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,2290193,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,255607,4.0,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,1508032,5.0,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate

In [45]:
print(df.tail())

     mal_id                          title                   title_english  \
495   32867   Bungou Stray Dogs 2nd Season              Bungo Stray Dogs 2
496   33674          No Game No Life: Zero          No Game, No Life: Zero
497     962               Aria the Natural                Aria the Natural
498     853         Ouran Koukou Host Club     Ouran High School Host Club
499    1889  Higurashi no Naku Koro ni Kai  Higurashi: When They Cry – Kai

      type        source  episodes           status  airing  \
495     TV         Manga      12.0  Finished Airing   False
496  Movie   Light novel       1.0  Finished Airing   False
497     TV         Manga      26.0  Finished Airing   False
498     TV         Manga      26.0  Finished Airing   False
499     TV  Visual novel      24.0  Finished Airing   False

                             rating  score  ...   rank  popularity  members  \
495  R - 17+ (violence & profanity)   8.16  ...  489.0         209   946655
496       PG-13 - Teens 13 or older   8.16  ...  493.0         210   943540
497                    G - All Ages   8.16  ...  488.0        2610    85481
498       PG-13 - Teens 13 or older   8.16  ...  494.0         136  1220509
499  R - 17+ (violence & profanity)   8.16  ...  490.0         488   518194

     favorites                                           synopsis    year  \
495       6855  Despite their differences in position, three m...  2016.0
496       7971  In ancient Disboard, Riku is an angry, young w...     NaN
497        832  Akari Mizunashi continues her training to beco...  2006.0
498      36917  Haruhi Fujioka is a studious girl who has rece...  2006.0
499       7642  In the small village of Hinamizawa, Rika Furud...  2007.0

                        genres         studios  \
495            Action, Mystery           Bones
496    Drama, Fantasy, Romance        Madhouse
497      Sci-Fi, Slice of Life  HAL Film Maker
498            Comedy, Romance           Bones
499  Horror, Mystery, Suspense     Studio Deen

                                                   url Episodes
495  https://myanimelist.net/anime/32867/Bungou_Str...        0
496  https://myanimelist.net/anime/33674/No_Game_No...        0
497  https://myanimelist.net/anime/962/Aria_the_Nat...        0
498  https://myanimelist.net/anime/853/Ouran_Koukou...        0
499  https://myanimelist.net/anime/1889/Higurashi_n...        0

[5 rows x 21 columns]

In [46]:
print(df.shape)

(500, 21)

In [47]:
print(df.dtypes)

mal_id             int64
title             object
title_english     object
type              object
source            object
episodes         float64
status            object
airing              bool
rating            object
score            float64
scored_by          int64
rank             float64
popularity         int64
members            int64
favorites          int64
synopsis          object
year             float64
genres            object
studios           object
url               object
Episodes           int64
dtype: object

In [48]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   mal_id         500 non-null    int64
 1   title          500 non-null    object
 2   title_english  458 non-null    object
 3   type           500 non-null    object
 4   source         500 non-null    object
 5   episodes       492 non-null    float64
 6   status         500 non-null    object
 7   airing         500 non-null    bool
 8   rating         500 non-null    object
 9   score          500 non-null    float64
 10  scored_by      500 non-null    int64
 11  rank           492 non-null    float64
 12  popularity     500 non-null    int64
 13  members        500 non-null    int64
 14  favorites      500 non-null    int64
 15  synopsis       500 non-null    object
 16  year           297 non-null    float64
 17  genres         494 non-null    object
 18  studios        498 non-null    object
 19  url            500 non-null    object
 20  Episodes       500 non-null    int64
dtypes: bool(1), float64(4), int64(6), object(10)
memory usage: 78.7+ KB
None

In [49]:
print(df.describe())

             mal_id    episodes       score     scored_by        rank  \
count    500.000000  492.000000  500.000000  5.000000e+02  492.000000
mean   30996.616000   18.357724    8.428940  3.271719e+05  246.552846
std    20276.672967   35.417988    0.222604  4.517006e+05  142.217810
min        1.000000    1.000000    8.160000  9.190000e+02    1.000000
25%    10143.250000    1.000000    8.250000  4.857050e+04  123.750000
50%    35847.000000   12.000000    8.370000  1.519620e+05  246.500000
75%    49393.500000   24.000000    8.562500  4.098580e+05  369.250000
max    63019.000000  500.000000    9.280000  3.038808e+06  494.000000

         popularity       members      favorites         year     Episodes
count    500.000000  5.000000e+02     500.000000   297.000000   500.000000
mean    1559.430000  5.789175e+05   13815.252000  2015.070707     4.022000
std     1919.380637  6.924760e+05   29497.765969     9.007038    89.934654
min        1.000000  2.212000e+03      24.000000  1970.000000     0.000000
25%      294.750000  1.133312e+05     852.000000  2010.000000     0.000000
50%      839.500000  3.296165e+05    3453.500000  2017.000000     0.000000
75%     2174.250000  7.721738e+05   13553.750000  2022.000000     0.000000
max    12270.000000  4.316356e+06  249284.000000  2026.000000  2011.000000

In [50]:
print(df.isnull().sum())

mal_id             0
title              0
title_english     42
type               0
source             0
episodes           8
status             0
airing             0
rating             0
score              0
scored_by          0
rank               8
popularity         0
members            0
favorites          0
synopsis           0
year             203
genres             6
studios            2
url                0
Episodes           0
dtype: int64

In [51]:
print(df.duplicated().sum())

0

In [56]:
clean_df = df.dropna()
df

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,1.0,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,...,2.0,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...,0
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,4.0,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,5.0,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,32867,Bungou Stray Dogs 2nd Season,Bungo Stray Dogs 2,TV,Manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,489.0,209,946655,6855,"Despite their differences in position, three m...",2016.0,"Action, Mystery",Bones,https://myanimelist.net/anime/32867/Bungou_Str...,0
496,33674,No Game No Life: Zero,"No Game, No Life: Zero",Movie,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,493.0,210,943540,7971,"In ancient Disboard, Riku is an angry, young w...",NaN,"Drama, Fantasy, Romance",Madhouse,https://myanimelist.net/anime/33674/No_Game_No...,0
497,962,Aria the Natural,Aria the Natural,TV,Manga,26.0,Finished Airing,False,G - All Ages,8.16,...,488.0,2610,85481,832,Akari Mizunashi continues her training to beco...,2006.0,"Sci-Fi, Slice of Life",HAL Film Maker,https://myanimelist.net/anime/962/Aria_the_Nat...,0
498,853,Ouran Koukou Host Club,Ouran High School Host Club,TV,Manga,26.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,494.0,136,1220509,36917,Haruhi Fujioka is a studious girl who has rece...,2006.0,"Comedy, Romance",Bones,https://myanimelist.net/anime/853/Ouran_Koukou...,0
499,1889,Higurashi no Naku Koro ni Kai,Higurashi: When They Cry – Kai,TV,Visual novel,24.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,490.0,488,518194,7642,"In the small village of Hinamizawa, Rika Furud...",2007.0,"Horror, Mystery, Suspense",Studio Deen,https://myanimelist.net/anime/1889/Higurashi_n...,0

In [57]:
df[df['score'] > 9]
df

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,1.0,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,...,2.0,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...,0
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,4.0,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,5.0,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,32867,Bungou Stray Dogs 2nd Season,Bungo Stray Dogs 2,TV,Manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,489.0,209,946655,6855,"Despite their differences in position, three m...",2016.0,"Action, Mystery",Bones,https://myanimelist.net/anime/32867/Bungou_Str...,0
496,33674,No Game No Life: Zero,"No Game, No Life: Zero",Movie,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,493.0,210,943540,7971,"In ancient Disboard, Riku is an angry, young w...",NaN,"Drama, Fantasy, Romance",Madhouse,https://myanimelist.net/anime/33674/No_Game_No...,0
497,962,Aria the Natural,Aria the Natural,TV,Manga,26.0,Finished Airing,False,G - All Ages,8.16,...,488.0,2610,85481,832,Akari Mizunashi continues her training to beco...,2006.0,"Sci-Fi, Slice of Life",HAL Film Maker,https://myanimelist.net/anime/962/Aria_the_Nat...,0
498,853,Ouran Koukou Host Club,Ouran High School Host Club,TV,Manga,26.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,494.0,136,1220509,36917,Haruhi Fujioka is a studious girl who has rece...,2006.0,"Comedy, Romance",Bones,https://myanimelist.net/anime/853/Ouran_Koukou...,0
499,1889,Higurashi no Naku Koro ni Kai,Higurashi: When They Cry – Kai,TV,Visual novel,24.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,490.0,488,518194,7642,"In the small village of Hinamizawa, Rika Furud...",2007.0,"Horror, Mystery, Suspense",Studio Deen,https://myanimelist.net/anime/1889/Higurashi_n...,0

In [59]:
df[df['episodes'] > 50]

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
6,28977,Gintama°,Gintama Season 4,TV,Manga,51.0,Finished Airing,False,PG-13 - Teens 13 or older,9.05,...,8.0,348,686377,17445,"Gintoki, Shinpachi, and Kagura return as the f...",2015.0,"Action, Comedy, Sci-Fi",Bandai Namco Pictures,https://myanimelist.net/anime/28977/Gintama°,0
8,11061,Hunter x Hunter (2011),Hunter x Hunter,TV,Manga,148.0,Finished Airing,False,PG-13 - Teens 13 or older,9.03,...,9.0,8,3151639,227808,Hunters devote themselves to accomplishing haz...,2011.0,"Action, Adventure, Fantasy",Madhouse,https://myanimelist.net/anime/11061/Hunter_x_H...,2011
10,9969,Gintama',Gintama Season 2,TV,Manga,51.0,Finished Airing,False,PG-13 - Teens 13 or older,9.02,...,11.0,406,608363,8569,"After a one-year hiatus, Shinpachi Shimura ret...",2011.0,"Action, Comedy, Sci-Fi",Sunrise,https://myanimelist.net/anime/9969/Gintama,0
12,820,Ginga Eiyuu Densetsu,Legend of the Galactic Heroes,OVA,Novel,110.0,Finished Airing,False,R - 17+ (violence & profanity),9.02,...,10.0,756,358962,17689,The 150-year-long stalemate between the two in...,NaN,"Drama, Sci-Fi","K-Factory, Kitty Film Mitaka Studio",https://myanimelist.net/anime/820/Ginga_Eiyuu_...,0
18,918,Gintama,Gintama,TV,Manga,201.0,Finished Airing,False,PG-13 - Teens 13 or older,8.93,...,19.0,147,1146253,61656,Edo is a city that was home to the vigor and a...,2006.0,"Action, Comedy, Sci-Fi",Sunrise,https://myanimelist.net/anime/918/Gintama,0
24,19,Monster,Monster,TV,Manga,74.0,Finished Airing,False,R+ - Mild Nudity,8.89,...,25.0,119,1308032,61307,"Dr. Kenzou Tenma, an elite neurosurgeon recent...",2004.0,"Drama, Mystery, Suspense",Madhouse,https://myanimelist.net/anime/19/Monster,0
40,263,Hajime no Ippo,Fighting Spirit,TV,Manga,75.0,Finished Airing,False,PG-13 - Teens 13 or older,8.78,...,37.0,349,685352,24996,"In his father's absence, teenager Ippo Makunou...",2000.0,Sports,Madhouse,https://myanimelist.net/anime/263/Hajime_no_Ippo,0
131,60557,Fanren Xiu Xian Zhuan 4th Season,A Record Of Mortal's Journey To Immortality 4t...,ONA,Web novel,52.0,Finished Airing,False,PG-13 - Teens 13 or older,8.55,...,130.0,11492,2741,43,Fourth season of Fanren Xiu Xian Zhuan.,NaN,"Action, Adventure, Fantasy","Original Force, Wonder Cat Animation",https://myanimelist.net/anime/60557/Fanren_Xiu...,0
139,170,Slam Dunk,Slam Dunk,TV,Manga,101.0,Finished Airing,False,PG-13 - Teens 13 or older,8.55,...,131.0,822,335363,8095,"Hanamichi Sakuragi, infamous for his temper, m...",1993.0,Sports,Toei Animation,https://myanimelist.net/anime/170/Slam_Dunk,0
172,12431,Uchuu Kyoudai,Space Brothers,TV,Manga,99.0,Finished Airing,False,PG-13 - Teens 13 or older,8.48,...,173.0,1319,209572,3946,"On a fateful summer night in 2006, Mutta Nanba...",2012.0,Comedy,A-1 Pictures,https://myanimelist.net/anime/12431/Uchuu_Kyoudai,0
185,392,Yuu☆Yuu☆Hakusho,Yu Yu Hakusho: Ghost Files,TV,Manga,112.0,Finished Airing,False,PG-13 - Teens 13 or older,8.46,...,183.0,304,748080,24559,"One fateful day, Yuusuke Urameshi, a 14-year-o...",1992.0,"Action, Supernatural",Studio Pierrot,https://myanimelist.net/anime/392/Yuu☆Yuu☆Hakusho,0
201,136,Hunter x Hunter,Hunter x Hunter,TV,Manga,62.0,Finished Airing,False,PG-13 - Teens 13 or older,8.43,...,204.0,381,643121,12117,Hunters are specialized in a wide variety of f...,1999.0,"Action, Adventure, Fantasy",Nippon Animation,https://myanimelist.net/anime/136/Hunter_x_Hunter,0
202,51039,Doupo Cangqiong: Nian Fan,Battle Through The Heavens Season 5,ONA,Web novel,209.0,Currently Airing,True,PG-13 - Teens 13 or older,8.43,...,201.0,6650,12034,394,Fifth season of Doupo Cangqiong.,NaN,"Action, Adventure, Fantasy",Motion Magic,https://myanimelist.net/anime/51039/Doupo_Cang...,0
218,33255,Saiki Kusuo no Ψ-nan,The Disastrous Life of Saiki K.,TV,Manga,120.0,Finished Airing,False,PG-13 - Teens 13 or older,8.41,...,218.0,130,1238800,33591,"To the average person, psychic abilities might...",2016.0,Comedy,"J.C.Staff, Egg Firm",https://myanimelist.net/anime/33255/Saiki_Kusu...,0
245,56524,Tunshi Xingkong 4th Season,Swallowed Star 4th Season,ONA,Web novel,175.0,Currently Airing,True,PG-13 - Teens 13 or older,8.37,...,249.0,8976,5756,153,Fourth season of Tunshi Xingkong.,NaN,"Action, Adventure, Fantasy, Sci-Fi",Sparkly Key Animation Studio,https://myanimelist.net/anime/56524/Tunshi_Xin...,0
257,2402,Ashita no Joe,Tomorrow's Joe,TV,Manga,79.0,Finished Airing,False,PG-13 - Teens 13 or older,8.36,...,251.0,2196,111264,2409,"Joe Yabuki is a troubled youth, whose only sol...",1970.0,"Drama, Sports",Mushi Production,https://myanimelist.net/anime/2402/Ashita_no_Joe,0
263,37822,Douluo Dalu 2nd Season,Soul Land,ONA,Novel,237.0,Finished Airing,False,PG-13 - Teens 13 or older,8.36,...,254.0,5079,23834,501,Second season of Douluo Dalu.,NaN,"Action, Adventure, Fantasy",Sparkly Key Animation Studio,https://myanimelist.net/anime/37822/Douluo_Dal...,0
308,30230,Diamond no Ace: Second Season,Ace of Diamond: Second Season,TV,Manga,51.0,Finished Airing,False,PG-13 - Teens 13 or older,8.31,...,301.0,1751,149645,1122,"After the National Tournament, the Seidou High...",2015.0,Sports,"Production I.G, Madhouse",https://myanimelist.net/anime/30230/Diamond_no...,0
337,1735,Naruto: Shippuuden,Naruto Shippuden,TV,Manga,500.0,Finished Airing,False,PG-13 - Teens 13 or older,8.29,...,321.0,15,2721147,119705,It has been two and a half years since Naruto ...,2007.0,"Action, Adventure, Fantasy",Studio Pierrot,https://myanimelist.net/anime/1735/Naruto__Shi...,0
343,38731,Diamond no Ace: Act II,Ace of Diamond Act II,TV,Manga,52.0,Finished Airing,False,PG-13 - Teens 13 or older,8.28,...,333.0,2361,100755,1082,The hallowed ground of Koshien Stadium is the ...,2019.0,Sports,Madhouse,https://myanimelist.net/anime/38731/Diamond_no...,0
345,2150,Tanoshii Muumin Ikka,Moomin,TV,Book,78.0,Finished Airing,False,G - All Ages,8.28,...,339.0,4410,33010,857,"Spring has finally arrived in Moomin Valley, g...",1990.0,"Adventure, Fantasy, Slice of Life",Telescreen,https://myanimelist.net/anime/2150/Tanoshii_Mu...,0
351,45,Rurouni Kenshin: Meiji Kenkaku Romantan,Rurouni Kenshin,TV,Manga,94.0,Finished Airing,False,PG-13 - Teens 13 or older,8.27,...,340.0,480,522768,10368,In the final years of the Bakumatsu era lived ...,1996.0,"Action, Comedy, Romance","Gallop, Studio Deen",https://myanimelist.net/anime/45/Rurouni_Kensh...,0
402,56215,Yi Nian Yong Heng 3rd Season,A Will Eternal 3rd Season,ONA,Web novel,59.0,Finished Airing,False,PG-13 - Teens 13 or older,8.22,...,408.0,10182,4026,44,After Bai Xiaochun merged the four downstream ...,NaN,"Action, Adventure, Comedy, Fantasy",B.CMAY PICTURES,https://myanimelist.net/anime/56215/Yi_Nian_Yo...,0
426,813,Dragon Ball Z,Dragon Ball Z,TV,Manga,291.0,Finished Airing,False,PG-13 - Teens 13 or older,8.21,...,417.0,116,1316967,41952,Five years after winning the World Martial Art...,1989.0,"Action, Adventure, Comedy, Fantasy",Toei Animation,https://myanimelist.net/anime/813/Dragon_Ball_Z,0
436,1453,Maison Ikkoku,Maison Ikkoku,TV,Manga,96.0,Finished Airing,False,R+ - Mild Nudity,8.20,...,425.0,2673,82342,1906,"In the town of Clock Hill, there is an old boa...",1986.0,"Comedy, Drama, Romance",Studio Deen,https://myanimelist.net/anime/1453/Maison_Ikkoku,0
442,9863,SKET Dance,SKET Dance,TV,Manga,77.0,Finished Airing,False,PG-13 - Teens 13 or older,8.20,...,430.0,1177,237422,3275,At Kaimei High School there is a special club ...,2011.0,Comedy,Tatsunoko Production,https://myanimelist.net/anime/9863/SKET_Dance,0
453,49574,Yi Nian Yong Heng 2nd Season,A Will Eternal 2nd Season,ONA,Web novel,54.0,Finished Airing,False,PG-13 - Teens 13 or older,8.19,...,449.0,7402,9273,102,"To avoid a war between the two sects, Bai Xiao...",NaN,"Action, Adventure, Fantasy",B.CMAY PICTURES,https://myanimelist.net/anime/49574/Yi_Nian_Yo...,0
472,232,Cardcaptor Sakura,Cardcaptor Sakura,TV,Manga,70.0,Finished Airing,False,PG - Children,8.18,...,453.0,533,482783,14696,Ten-year-old Sakura Kinomoto is an ordinary fo...,1998.0,"Adventure, Comedy, Drama, Romance",Madhouse,https://myanimelist.net/anime/232/Cardcaptor_S...,0

In [60]:
df[df['type'] == 'TV']

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,1.0,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,...,2.0,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...,0
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,5.0,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0
5,38524,Shingeki no Kyojin Season 3 Part 2,Attack on Titan Season 3 Part 2,TV,Manga,10.0,Finished Airing,False,R - 17+ (violence & profanity),9.05,...,6.0,20,2560224,62801,Seeking to restore humanity's diminishing hope...,2019.0,"Action, Drama, Suspense",Wit Studio,https://myanimelist.net/anime/38524/Shingeki_n...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,57181,Ao no Hako,Blue Box,TV,Manga,25.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,487.0,880,317439,4284,"Every morning, incoming first-year Taiki Inoma...",2024.0,"Romance, Sports",Telecom Animation Film,https://myanimelist.net/anime/57181/Ao_no_Hako,0
495,32867,Bungou Stray Dogs 2nd Season,Bungo Stray Dogs 2,TV,Manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,489.0,209,946655,6855,"Despite their differences in position, three m...",2016.0,"Action, Mystery",Bones,https://myanimelist.net/anime/32867/Bungou_Str...,0
497,962,Aria the Natural,Aria the Natural,TV,Manga,26.0,Finished Airing,False,G - All Ages,8.16,...,488.0,2610,85481,832,Akari Mizunashi continues her training to beco...,2006.0,"Sci-Fi, Slice of Life",HAL Film Maker,https://myanimelist.net/anime/962/Aria_the_Nat...,0
498,853,Ouran Koukou Host Club,Ouran High School Host Club,TV,Manga,26.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,494.0,136,1220509,36917,Haruhi Fujioka is a studious girl who has rece...,2006.0,"Comedy, Romance",Bones,https://myanimelist.net/anime/853/Ouran_Koukou...,0
499,1889,Higurashi no Naku Koro ni Kai,Higurashi: When They Cry – Kai,TV,Visual novel,24.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,490.0,488,518194,7642,"In the small village of Hinamizawa, Rika Furud...",2007.0,"Horror, Mystery, Suspense",Studio Deen,https://myanimelist.net/anime/1889/Higurashi_n...,0

In [61]:
df[df['status'] == 'Finished Airing']

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,1.0,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,4.0,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,5.0,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0
5,38524,Shingeki no Kyojin Season 3 Part 2,Attack on Titan Season 3 Part 2,TV,Manga,10.0,Finished Airing,False,R - 17+ (violence & profanity),9.05,...,6.0,20,2560224,62801,Seeking to restore humanity's diminishing hope...,2019.0,"Action, Drama, Suspense",Wit Studio,https://myanimelist.net/anime/38524/Shingeki_n...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,32867,Bungou Stray Dogs 2nd Season,Bungo Stray Dogs 2,TV,Manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,489.0,209,946655,6855,"Despite their differences in position, three m...",2016.0,"Action, Mystery",Bones,https://myanimelist.net/anime/32867/Bungou_Str...,0
496,33674,No Game No Life: Zero,"No Game, No Life: Zero",Movie,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,493.0,210,943540,7971,"In ancient Disboard, Riku is an angry, young w...",NaN,"Drama, Fantasy, Romance",Madhouse,https://myanimelist.net/anime/33674/No_Game_No...,0
497,962,Aria the Natural,Aria the Natural,TV,Manga,26.0,Finished Airing,False,G - All Ages,8.16,...,488.0,2610,85481,832,Akari Mizunashi continues her training to beco...,2006.0,"Sci-Fi, Slice of Life",HAL Film Maker,https://myanimelist.net/anime/962/Aria_the_Nat...,0
498,853,Ouran Koukou Host Club,Ouran High School Host Club,TV,Manga,26.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,494.0,136,1220509,36917,Haruhi Fujioka is a studious girl who has rece...,2006.0,"Comedy, Romance",Bones,https://myanimelist.net/anime/853/Ouran_Koukou...,0
499,1889,Higurashi no Naku Koro ni Kai,Higurashi: When They Cry – Kai,TV,Visual novel,24.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,490.0,488,518194,7642,"In the small village of Hinamizawa, Rika Furud...",2007.0,"Horror, Mystery, Suspense",Studio Deen,https://myanimelist.net/anime/1889/Higurashi_n...,0

In [62]:
df.sort_values('score', ascending=False)

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,1.0,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,...,2.0,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...,0
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,4.0,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,5.0,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,32867,Bungou Stray Dogs 2nd Season,Bungo Stray Dogs 2,TV,Manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,489.0,209,946655,6855,"Despite their differences in position, three m...",2016.0,"Action, Mystery",Bones,https://myanimelist.net/anime/32867/Bungou_Str...,0
496,33674,No Game No Life: Zero,"No Game, No Life: Zero",Movie,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,493.0,210,943540,7971,"In ancient Disboard, Riku is an angry, young w...",NaN,"Drama, Fantasy, Romance",Madhouse,https://myanimelist.net/anime/33674/No_Game_No...,0
497,962,Aria the Natural,Aria the Natural,TV,Manga,26.0,Finished Airing,False,G - All Ages,8.16,...,488.0,2610,85481,832,Akari Mizunashi continues her training to beco...,2006.0,"Sci-Fi, Slice of Life",HAL Film Maker,https://myanimelist.net/anime/962/Aria_the_Nat...,0
498,853,Ouran Koukou Host Club,Ouran High School Host Club,TV,Manga,26.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,494.0,136,1220509,36917,Haruhi Fujioka is a studious girl who has rece...,2006.0,"Comedy, Romance",Bones,https://myanimelist.net/anime/853/Ouran_Koukou...,0
499,1889,Higurashi no Naku Koro ni Kai,Higurashi: When They Cry – Kai,TV,Visual novel,24.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,490.0,488,518194,7642,"In the small village of Hinamizawa, Rika Furud...",2007.0,"Horror, Mystery, Suspense",Studio Deen,https://myanimelist.net/anime/1889/Higurashi_n...,0

In [63]:
df.sort_values('popularity')

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,rank,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes
122,16498,Shingeki no Kyojin,Attack on Titan,TV,Manga,25.0,Finished Airing,False,R - 17+ (violence & profanity),8.57,...,121.0,1,4316356,187384,"Centuries ago, mankind was slaughtered to near...",2013.0,"Action, Award Winning, Drama, Suspense",Wit Studio,https://myanimelist.net/anime/16498/Shingeki_n...,0
98,1535,Death Note,Death Note,TV,Manga,37.0,Finished Airing,False,R - 17+ (violence & profanity),8.62,...,97.0,2,4255809,184714,"Brutal murders, petty thefts, and senseless vi...",2006.0,"Supernatural, Suspense",Madhouse,https://myanimelist.net/anime/1535/Death_Note,0
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3.0,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0
173,30276,One Punch Man,One-Punch Man,TV,Web manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.48,...,171.0,4,3491486,66358,The seemingly unimpressive Saitama has a rathe...,2015.0,"Action, Comedy",Madhouse,https://myanimelist.net/anime/30276/One_Punch_Man,0
223,38000,Kimetsu no Yaiba,Demon Slayer: Kimetsu no Yaiba,TV,Manga,26.0,Finished Airing,False,R - 17+ (violence & profanity),8.41,...,221.0,5,3407810,94601,"Ever since the death of his father, the burden...",2019.0,"Action, Award Winning, Supernatural",ufotable,https://myanimelist.net/anime/38000/Kimetsu_no...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,56523,Tunshi Xingkong 3rd Season,Swallowed Star 3rd Season,ONA,Web novel,33.0,Finished Airing,False,PG-13 - Teens 13 or older,8.38,...,238.0,9463,4975,45,Third season of Tunshi Xingkong.,NaN,"Action, Adventure, Fantasy, Sci-Fi",Sparkly Key Animation Studio,https://myanimelist.net/anime/56523/Tunshi_Xin...,0
402,56215,Yi Nian Yong Heng 3rd Season,A Will Eternal 3rd Season,ONA,Web novel,59.0,Finished Airing,False,PG-13 - Teens 13 or older,8.22,...,408.0,10182,4026,44,After Bai Xiaochun merged the four downstream ...,NaN,"Action, Adventure, Comedy, Fantasy",B.CMAY PICTURES,https://myanimelist.net/anime/56215/Yi_Nian_Yo...,0
266,57067,Fanren Xiu Xian Zhuan: Xinghai Feichi,A Record Of Mortal's Journey To Immortality 3r...,ONA,Web novel,48.0,Finished Airing,False,PG-13 - Teens 13 or older,8.35,...,269.0,10323,3824,38,Third season of Fanren Xiu Xian Zhuan.,NaN,"Action, Adventure, Fantasy","Original Force, Wonder Cat Animation",https://myanimelist.net/anime/57067/Fanren_Xiu...,0
131,60557,Fanren Xiu Xian Zhuan 4th Season,A Record Of Mortal's Journey To Immortality 4t...,ONA,Web novel,52.0,Finished Airing,False,PG-13 - Teens 13 or older,8.55,...,130.0,11492,2741,43,Fourth season of Fanren Xiu Xian Zhuan.,NaN,"Action, Adventure, Fantasy","Original Force, Wonder Cat Animation",https://myanimelist.net/anime/60557/Fanren_Xiu...,0
446,60420,Cang Yuan Tu 2,The Demon Hunter 2,ONA,Web novel,36.0,Finished Airing,False,PG-13 - Teens 13 or older,8.19,...,440.0,12270,2212,24,Second season of Cang Yuan Tu.,NaN,"Action, Adventure, Fantasy","Shenman Entertainment, Tianshi Wenhua",https://myanimelist.net/anime/60420/Cang_Yuan_...,0

In [64]:
df.groupby('type')['score'].mean()

type
Movie         8.410877
Music         8.397143
ONA           8.415455
OVA           8.358235
PV            8.380000
Special       8.336667
TV            8.443401
TV Special    8.489091
Name: score, dtype: float64

In [65]:
df.groupby('status').size()

status
Currently Airing     20
Finished Airing     480
dtype: int64

In [66]:
df.groupby('source')['score'].max()

source
4-koma manga    8.73
Book            8.28
Game            8.64
Light novel     9.02
Manga           9.28
Mixed media     8.22
Music           8.62
Novel           9.02
Original        8.91
Other           8.39
Visual novel    9.07
Web manga       8.78
Web novel       8.67
Name: score, dtype: float64

In [67]:
df['type'].value_counts()

type
TV            297
Movie         114
ONA            44
OVA            17
TV Special     11
Special         9
Music           7
PV              1
Name: count, dtype: int64

In [68]:
df['source'].value_counts()

source
Manga           280
Original         68
Light novel      54
Web novel        25
Novel            23
Web manga        20
Visual novel     13
Game              6
4-koma manga      4
Other             4
Music             1
Book              1
Mixed media       1
Name: count, dtype: int64

In [70]:
def pop(x):
    if x < 100:
        return "Very Popular"
    elif x < 500:
        return "Popular"
    else:
        return "Normal"

df['pop_category'] = df['popularity'].apply(pop)
df

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes,pop_category
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0,Popular
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,...,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...,0,Normal
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0,Very Popular
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0,Normal
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0,Very Popular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,32867,Bungou Stray Dogs 2nd Season,Bungo Stray Dogs 2,TV,Manga,12.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,209,946655,6855,"Despite their differences in position, three m...",2016.0,"Action, Mystery",Bones,https://myanimelist.net/anime/32867/Bungou_Str...,0,Popular
496,33674,No Game No Life: Zero,"No Game, No Life: Zero",Movie,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,210,943540,7971,"In ancient Disboard, Riku is an angry, young w...",NaN,"Drama, Fantasy, Romance",Madhouse,https://myanimelist.net/anime/33674/No_Game_No...,0,Popular
497,962,Aria the Natural,Aria the Natural,TV,Manga,26.0,Finished Airing,False,G - All Ages,8.16,...,2610,85481,832,Akari Mizunashi continues her training to beco...,2006.0,"Sci-Fi, Slice of Life",HAL Film Maker,https://myanimelist.net/anime/962/Aria_the_Nat...,0,Normal
498,853,Ouran Koukou Host Club,Ouran High School Host Club,TV,Manga,26.0,Finished Airing,False,PG-13 - Teens 13 or older,8.16,...,136,1220509,36917,Haruhi Fujioka is a studious girl who has rece...,2006.0,"Comedy, Romance",Bones,https://myanimelist.net/anime/853/Ouran_Koukou...,0,Popular
499,1889,Higurashi no Naku Koro ni Kai,Higurashi: When They Cry – Kai,TV,Visual novel,24.0,Finished Airing,False,R - 17+ (violence & profanity),8.16,...,488,518194,7642,"In the small village of Hinamizawa, Rika Furud...",2007.0,"Horror, Mystery, Suspense",Studio Deen,https://myanimelist.net/anime/1889/Higurashi_n...,0,Popular

In [71]:
df['title'].str.upper()

0                     SOUSOU NO FRIEREN
1          SOUSOU NO FRIEREN 2ND SEASON
2      FULLMETAL ALCHEMIST: BROTHERHOOD
3          CHAINSAW MAN MOVIE: REZE-HEN
4                           STEINS;GATE
                     ...
495        BUNGOU STRAY DOGS 2ND SEASON
496               NO GAME NO LIFE: ZERO
497                    ARIA THE NATURAL
498              OURAN KOUKOU HOST CLUB
499       HIGURASHI NO NAKU KORO NI KAI
Name: title, Length: 500, dtype: object

In [72]:
df['title'].apply(len)

0      17
1      28
2      32
3      28
4      11
       ..
495    28
496    21
497    16
498    22
499    29
Name: title, Length: 500, dtype: int64

In [73]:
df[df['title'].str.contains('Naruto', na=False)]

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes,pop_category
236,53236,Road of Naruto,Road of Naruto,PV,Manga,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.38,...,4078,38856,112,"In celebration of 20 years of Naruto, Studio P...",NaN,"Action, Fantasy",Studio Pierrot,https://myanimelist.net/anime/53236/Road_of_Na...,0,Normal
337,1735,Naruto: Shippuuden,Naruto Shippuden,TV,Manga,500.0,Finished Airing,False,PG-13 - Teens 13 or older,8.29,...,15,2721147,119705,It has been two and a half years since Naruto ...,2007.0,"Action, Adventure, Fantasy",Studio Pierrot,https://myanimelist.net/anime/1735/Naruto__Shi...,0,Very Popular

In [74]:
df['score'].mean()

np.float64(8.428939999999999)

In [75]:
df['episodes'].max()

np.float64(500.0)

In [76]:
df['members'].sum()

np.int64(289458758)

In [77]:
df.nlargest(10, 'score')

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes,pop_category
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0,Popular
1,59978,Sousou no Frieren 2nd Season,Frieren: Beyond Journey's End Season 2,TV,Manga,10.0,Currently Airing,True,PG-13 - Teens 13 or older,9.16,...,644,414180,5476,"Following the First-Class Mage Exam, the trio—...",2026.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/59978/Sousou_no_...,0,Normal
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,TV,Manga,64.0,Finished Airing,False,R - 17+ (violence & profanity),9.11,...,3,3645704,240910,After a horrific alchemy experiment goes wrong...,2009.0,"Action, Adventure, Drama, Fantasy",Bones,https://myanimelist.net/anime/5114/Fullmetal_A...,0,Very Popular
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0,Normal
4,9253,Steins;Gate,Steins;Gate,TV,Visual novel,24.0,Finished Airing,False,PG-13 - Teens 13 or older,9.07,...,14,2786505,201170,Eccentric scientist Rintarou Okabe has a never...,2011.0,"Drama, Sci-Fi, Suspense",White Fox,https://myanimelist.net/anime/9253/Steins_Gate,0,Very Popular
5,38524,Shingeki no Kyojin Season 3 Part 2,Attack on Titan Season 3 Part 2,TV,Manga,10.0,Finished Airing,False,R - 17+ (violence & profanity),9.05,...,20,2560224,62801,Seeking to restore humanity's diminishing hope...,2019.0,"Action, Drama, Suspense",Wit Studio,https://myanimelist.net/anime/38524/Shingeki_n...,0,Very Popular
6,28977,Gintama°,Gintama Season 4,TV,Manga,51.0,Finished Airing,False,PG-13 - Teens 13 or older,9.05,...,348,686377,17445,"Gintoki, Shinpachi, and Kagura return as the f...",2015.0,"Action, Comedy, Sci-Fi",Bandai Namco Pictures,https://myanimelist.net/anime/28977/Gintama°,0,Popular
7,39486,Gintama: The Final,Gintama: The Very Final,Movie,Manga,1.0,Finished Airing,False,PG-13 - Teens 13 or older,9.05,...,1513,180815,4638,Two years have passed following the Tendoshuu'...,NaN,"Action, Comedy, Drama, Sci-Fi",Bandai Namco Pictures,https://myanimelist.net/anime/39486/Gintama__T...,0,Normal
8,11061,Hunter x Hunter (2011),Hunter x Hunter,TV,Manga,148.0,Finished Airing,False,PG-13 - Teens 13 or older,9.03,...,8,3151639,227808,Hunters devote themselves to accomplishing haz...,2011.0,"Action, Adventure, Fantasy",Madhouse,https://myanimelist.net/anime/11061/Hunter_x_H...,2011,Very Popular
9,60022,One Piece Fan Letter,NaN,TV Special,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,9.02,...,1788,146484,2538,Although the golden age of piracy is about to ...,NaN,"Action, Adventure, Fantasy",Toei Animation,https://myanimelist.net/anime/60022/One_Piece_...,0,Normal

In [78]:
df.loc[df.groupby('type')['score'].idxmax()]

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes,pop_category
3,57555,Chainsaw Man Movie: Reze-hen,Chainsaw Man – The Movie: Reze Arc,Movie,Manga,1.0,Finished Airing,False,R - 17+ (violence & profanity),9.09,...,643,414906,12097,Despite the immediate challenges following bec...,NaN,"Action, Fantasy",MAPPA,https://myanimelist.net/anime/57555/Chainsaw_M...,0,Normal
62,55016,Idol,NaN,Music,Original,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.70,...,4775,27791,336,Music video for the song Idol by Yaosobi. The ...,NaN,NaN,Doga Kobo,https://myanimelist.net/anime/55016/Idol,0,Normal
44,60489,Takopii no Genzai,Takopi's Original Sin,ONA,Manga,6.0,Finished Airing,False,R - 17+ (violence & profanity),8.76,...,939,292240,6138,"A squid-like creature, known as a Happian, lea...",NaN,"Drama, Sci-Fi",Enishiya,https://myanimelist.net/anime/60489/Takopii_no...,0,Normal
12,820,Ginga Eiyuu Densetsu,Legend of the Galactic Heroes,OVA,Novel,110.0,Finished Airing,False,R - 17+ (violence & profanity),9.02,...,756,358962,17689,The 150-year-long stalemate between the two in...,NaN,"Drama, Sci-Fi","K-Factory, Kitty Film Mitaka Studio",https://myanimelist.net/anime/820/Ginga_Eiyuu_...,0,Normal
236,53236,Road of Naruto,Road of Naruto,PV,Manga,1.0,Finished Airing,False,PG-13 - Teens 13 or older,8.38,...,4078,38856,112,"In celebration of 20 years of Naruto, Studio P...",NaN,"Action, Fantasy",Studio Pierrot,https://myanimelist.net/anime/53236/Road_of_Na...,0,Normal
191,44087,Gintama: The Semi-Final,NaN,Special,Manga,2.0,Finished Airing,False,PG-13 - Teens 13 or older,8.45,...,2503,91900,268,As the war temporarily calms down and Edo rebu...,NaN,"Action, Comedy",Bandai Namco Pictures,https://myanimelist.net/anime/44087/Gintama__T...,0,Normal
0,52991,Sousou no Frieren,Frieren: Beyond Journey's End,TV,Manga,28.0,Finished Airing,False,PG-13 - Teens 13 or older,9.28,...,108,1353494,85889,During their decade-long quest to defeat the D...,2023.0,"Adventure, Drama, Fantasy",Madhouse,https://myanimelist.net/anime/52991/Sousou_no_...,0,Popular
9,60022,One Piece Fan Letter,NaN,TV Special,Light novel,1.0,Finished Airing,False,PG-13 - Teens 13 or older,9.02,...,1788,146484,2538,Although the golden age of piracy is about to ...,NaN,"Action, Adventure, Fantasy",Toei Animation,https://myanimelist.net/anime/60022/One_Piece_...,0,Normal

In [79]:
df[['episodes','score']].corr()

          episodes     score
episodes  1.000000  0.044068
score     0.044068  1.000000

In [80]:
df.sort_values('favorites', ascending=False).head(1)

,mal_id,title,title_english,type,source,episodes,status,airing,rating,score,...,popularity,members,favorites,synopsis,year,genres,studios,url,Episodes,pop_category
51,21,One Piece,One Piece,TV,Manga,NaN,Currently Airing,True,PG-13 - Teens 13 or older,8.73,...,17,2643713,249284,Barely surviving in a barrel after passing thr...,1999.0,"Action, Adventure, Fantasy",Toei Animation,https://myanimelist.net/anime/21/One_Piece,0,Very Popular