In [1]:
import numpy as np
import pandas as pd

In [2]:
print("Creating a DataFrame")

Creating a DataFrame

In [6]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [165000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [7]:
df

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 165000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2

       0   1         2       3
0   John  28  New York  165000
1   Anna  34     Paris   70000
2  Peter  29    Berlin   62000
3  Linda  42    London   85000

In [11]:
print("Selection and Indexing of Column")

Selection and Indexing of Column

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [14]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [15]:
print("Creating a New Column")

Creating a New Column

In [16]:
df2["Designation"] = ["Eng", "Doct", "Eng", "Doct"]

In [17]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York  165000         Eng
1   Anna   34     Paris   70000        Doct
2  Peter   29    Berlin   62000         Eng
3  Linda   42    London   85000        Doct

In [18]:
print("Removing a Column")

Removing a Column

In [21]:
df2.drop('Designation', axis = 1, inplace = True)

In [22]:
df2

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
print("Selecting Rows")

Selecting Rows

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df2.loc[[0, 1]]

   Name  Age      City  Salary
0  John   28  New York  165000
1  Anna   34     Paris   70000

In [28]:
print("Selecting Subsets of Rows and Columns")

Selecting Subsets of Rows and Columns

In [29]:
df2

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df2.loc[[0, 1]][["City", "Salary"]]

       City  Salary
0  New York  165000
1     Paris   70000

In [31]:
df2.loc[[2, 3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [32]:
print("Conditional Selection")

Conditional Selection

In [33]:
df2

    Name  Age      City  Salary
0   John   28  New York  165000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [36]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000